<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMmQaMub\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMmQaMub/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMmQaMub.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMmQaMub\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMmQaMub\App_KernelDevDebugContainer([
    'container.build_hash' => 'MmQaMub',
    'container.build_id' => '95f7f104',
    'container.build_time' => 1689056729,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMmQaMub');
